FROM gstreamer:base

WORKDIR /gstreamer

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install \
      libssl-dev tclsh

ARG SRT_VERSION=master
RUN git clone https://github.com/Haivision/srt.git && \
      cd srt && \
      ./configure && \
      make install

RUN cd ./gst-build/gst-build-branch && \
    meson build --reconfigure \
        -Dgst-plugins-bad:srt=enabled \

RUN cd ./gst-build/gst-build-branch && \
    ninja -C build install

